# Generated by Django 3.1.13 on 2021-07-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201130_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postindexpage',
            name='sub_site_categories',
        ),
    ]
