# Generated by Django 3.1.13 on 2021-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlascasestudies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlascasestudy',
            name='wp_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
