# Generated by Django 3.1.14 on 2022-02-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210825_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
