# Generated by Django 3.1.13 on 2021-07-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_auto_20201130_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationtype',
            name='sub_site',
        ),
        migrations.DeleteModel(
            name='PublicationTypeSubSite',
        ),
    ]
