# Generated by Django 3.1.13 on 2021-07-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_auto_20210705_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationtype',
            name='source',
        ),
    ]
