# Generated by Django 3.2.12 on 2022-03-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220302_1430'),
        ('core', '0003_docimportbridge_imageimportbridge'),
    ]

    operations = [
    ]
