# Generated by Django 3.2.12 on 2022-03-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lowerfooterlinks_upperfooterlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upperfooterlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='upperfooterlinks',
            name='setting',
        ),
        migrations.DeleteModel(
            name='LowerFooterLinks',
        ),
        migrations.DeleteModel(
            name='UpperFooterLinks',
        ),
    ]
