# Generated by Django 3.2.12 on 2022-03-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210825_1457'),
        ('core', '0005_lowerfooterlinks_upperfooterlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_fixed', models.BooleanField(default=False)),
                ('html_parsed', models.IntegerField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.basepage')),
            ],
        ),
        migrations.RemoveField(
            model_name='upperfooterlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='upperfooterlinks',
            name='setting',
        ),
        migrations.DeleteModel(
            name='LowerFooterLinks',
        ),
        migrations.DeleteModel(
            name='UpperFooterLinks',
        ),
    ]
