# Generated by Django 3.2.12 on 2022-03-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('core', '0006_auto_20220315_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_fixed', models.BooleanField(default=False)),
                ('html_parsed', models.IntegerField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
            ],
        ),
    ]
