# Generated by Django 3.2.12 on 2022-03-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('core', '0006_auto_20220316_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parselist',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page'),
        ),
    ]
