# Generated by Django 3.2.12 on 2022-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parselist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedmainmenuitem',
            name='caption',
            field=models.CharField(blank=True, help_text='Additional explanatory text which appears alongside this menu item', max_length=70),
        ),
    ]
