from django.core.management.base import BaseCommand
from cms.pages.models import BasePage
import logging

logger = logging.getLogger(__name__)
# some pages are autogenerated so for now lets ignore them


class Command(BaseCommand):

    help = "Identify and updated content groups for pages"

    def handle(self, *args, **options):
        pages = BasePage.objects.all()
        assert pages, "No pages existed."

        print("f{len(pages)} pages found.")
        for page in pages:
            logger.info(f"Considering {page}")
            print(page)
            print(dir(page))
            exit()
