# Generated by Django 3.1.13 on 2021-07-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_auto_20201130_1230"),
        ("posts", "0011_remove_postindexpage_sub_site_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogindexpage",
            name="sub_site_categories",
        ),
    ]
