# Generated by Django 3.1.12 on 2021-07-22 12:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('categorypage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.categorypage')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('documents', wagtail.fields.StreamField([('document_group', wagtail.blocks.StreamBlock([('document', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('summary', wagtail.blocks.RichTextBlock(required=False))])), ('document_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('summary', wagtail.blocks.RichTextBlock(required=False))])), ('document_embed', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock(required=False)), ('html', wagtail.blocks.RawHTMLBlock())])), ('free_text', wagtail.blocks.RichTextBlock())], group='Custom')), ('jump_menu', wagtail.blocks.StructBlock([('menu', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('menu_id', wagtail.blocks.CharBlock())])))], group='Custom')), ('named_anchor', wagtail.blocks.StructBlock([('anchor_id', wagtail.blocks.CharBlock()), ('heading', wagtail.blocks.CharBlock(required=False))], group='Custom'))], blank=True)),
                ('wp_id', models.PositiveIntegerField(null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('wp_slug', models.TextField(blank=True, null=True)),
                ('wp_link', models.TextField(blank=True, null=True)),
                ('component_fields', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('categories.categorypage',),
        ),
        migrations.CreateModel(
            name='PublicationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Publications Index Page',
                'verbose_name_plural': 'Publications Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicationPublicationTypeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_publication_type_relationship', to='publications.publication')),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.publicationtype')),
            ],
        ),
    ]
