# Generated by Django 3.2.13 on 2022-05-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_changelogentrylink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelogentrylink',
            options={'ordering': ['change_date']},
        ),
    ]
