# Generated by Django 3.1.13 on 2021-07-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20201130_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationindexpage',
            name='sub_site_publication_types',
        ),
    ]
