# Generated by Django 3.2.12 on 2022-03-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_toc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toc',
            old_name='page_id',
            new_name='page',
        ),
    ]
