# Generated by Django 3.2.12 on 2022-03-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_page_id_toc_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TOC',
        ),
    ]
