# Generated by Django 3.2.13 on 2022-05-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220512_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentspage',
            name='md_description',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='md_gateway_ref',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='md_owner',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='md_pac_reference',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='md_gateway_ref',
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='md_description',
            field=models.TextField(blank=True, verbose_name='Description of content'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='md_owner',
            field=models.TextField(blank=True, verbose_name='Content Owner'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='md_pac_reference',
            field=models.TextField(blank=True, verbose_name='PAC Reference'),
        ),
    ]
