# Generated by Django 3.2.13 on 2022-05-18 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20220516_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='The time the changes were made')),
                ('change_description', models.TextField(verbose_name='Description of the changes')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='pages.basepage')),
            ],
            options={
                'ordering': ['change_date'],
            },
        ),
    ]
