# Generated by Django 3.1.12 on 2021-06-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_blogcategory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basepage',
            old_name='categories',
            new_name='groups',
        ),
    ]
