# A list of all the new categories, with associated information used to create the category object
CATEGORIES = {
    "6cs-live-bulletin": {"name": "6Cs Live! Bulletin"},
    "7-days-consistency-of-care": {"name": "7 days, consistency of care"},
    "a-e-weekly-data": {"name": "A & E weekly data"},
    "a-greener-nhs": {"name": "A greener NHS"},
    "abortion-statistics-for-england-and-wales": {
        "name": "Abortion statistics for England and Wales"
    },
    "about-us": {"name": "About us"},
    "academic-health-science-network": {"name": "Academic Health Science Network"},
    "accessible-information-standard": {"name": "Accessible Information Standard"},
    "acute-and-emergency-care": {"name": "Acute and Emergency Care"},
    "admission-events-referrals-and-attendances": {
        "name": "Admission events, referrals and attendances"
    },
    "ageing-well": {"name": "Ageing well"},
    "alistair-burns": {"name": "Alistair Burns"},
    "allied-health-professionals-bulletin": {
        "name": "Allied health professionals bulletin"
    },
    "allied-health-professionals": {"name": "Allied Health Professionals"},
    "ambulance-quality-indicators": {"name": "Ambulance Quality Indicators"},
    "ann-driver": {"name": "Ann Driver"},
    "annual-cancer-waiting-times-reports": {
        "name": "Annual cancer waiting times reports"
    },
    "annual-report": {"name": "Annual report"},
    "armed-forces": {"name": "Armed forces"},
    "artificial-intelligence": {"name": "Artificial intelligence"},
    "asthma": {"name": "Asthma"},
    "barbara-hakin": {"name": "Barbara Hakin"},
    "bed-availability-and-occupancy": {"name": "Bed Availability and Occupancy"},
    "better-care-fund": {"name": "Better Care Fund"},
    "blogs": {"name": "Blogs"},
    "board-meetings": {"name": "Board meetings"},
    "breastfeeding-quarterly-statistical-releases": {
        "name": "Breastfeeding quarterly statistical releases"
    },
    "bulletin-for-ccgs": {"name": "Bulletin for CCGs"},
    "business-plan-2012-2015-indicators-and-other-key-data": {
        "name": "Business plan 2012-2015: indicators and other key data"
    },
    "business-plan-quarterly-data-summaries": {
        "name": "Business Plan Quarterly Data Summaries"
    },
    "business-plan": {"name": "Business plan"},
    "cancelled-elective-operations": {"name": "Cancelled elective operations"},
    "cancer": {"name": "Cancer"},
    "capability-building": {"name": "Capability Building"},
    "cardiovascular": {"name": "Cardiovascular"},
    "care-planning": {"name": "Care Planning"},
    "carers": {"name": "Carers"},
    "ccg-learning-and-support-tool": {"name": "CCG learning and support tool"},
    "ccg-learning-network-news": {"name": "CCG learning network news"},
    "central-alerting-system-data": {"name": "Central Alerting System Data"},
    "chief-nursing-officer-bulletin": {"name": "Chief nursing officer bulletin"},
    "chief-scientific-officer-bulletin": {"name": "Chief Scientific Officer bulletin"},
    "children-and-young-people": {"name": "Children and young people"},
    "civil-service-people-survey-dh-results": {
        "name": "Civil Service People Survey: DH results"
    },
    "clinical-audit": {"name": "Clinical audit"},
    "coffee-break": {"name": "Coffee break"},
    "commissioner-based-waiting-times-for-cancer-patients": {
        "name": "Commissioner based waiting times for cancer patients"
    },
    "commissioning-support-bulletin": {"name": "Commissioning Support Bulletin"},
    "commissioning": {"name": "Commissioning"},
    "community-services": {"name": "Community Services"},
    "conflicts-of-interest-audit-and-training": {
        "name": "Conflicts of interest audit and training"
    },
    "consultant-led-referral-to-treatment-waiting-times-statistics": {
        "name": "Consultant-led Referral to treatment waiting times statistics"
    },
    "coronavirus": {"name": "Coronavirus"},
    "covid-19": {"name": "COVID-19"},
    "critical-care-bed-capacity-and-cancelled-urgent-operations": {
        "name": "Critical care bed capacity and cancelled urgent operations"
    },
    "culture-and-leadership": {"name": "Culture and Leadership"},
    "david-nicholson": {"name": "David Nicholson"},
    "delayed-transfers-of-care": {"name": "Delayed Transfers of Care"},
    "demand-and-capacity": {"name": "Demand and Capacity"},
    "dementia": {"name": "Dementia"},
    "dental-care": {"name": "Dental care"},
    "departmental-spending-over-25000": {"name": "Departmental spending over £25,000"},
    "departmental-spending-over-500": {"name": "Departmental spending over £500"},
    "dh-business-expenses": {"name": "DH business expenses"},
    "dh-complaints": {"name": "DH complaints"},
    "diabetes-and-kidney-care": {"name": "Diabetes and Kidney Care"},
    "diabetes": {"name": "Diabetes"},
    "diagnostic-imaging-dataset": {"name": "Diagnostic imaging dataset"},
    "diagnostics-waiting-times-and-activity-data": {
        "name": "Diagnostics waiting times and activity data"
    },
    "diagnostics": {"name": "Diagnostics"},
    "digital": {"name": "Digital"},
    "direct-access-audiology-waiting-times": {
        "name": "Direct Access Audiology waiting times"
    },
    "dr-johnny-marshall": {"name": "Dr Johnny Marshall"},
    "efficiencies": {"name": "Efficiencies"},
    "efficiency-and-waste-reduction": {"name": "Efficiency and Waste Reduction"},
    "elective-care": {"name": "Elective care"},
    "emergency-preparedness-resilience-and-response": {
        "name": "Emergency Preparedness, Resilience and Response"
    },
    "end-of-life-care": {"name": "End of life care"},
    "equality-and-diversity": {"name": "Equality and diversity"},
    "estates": {"name": "Estates"},
    "eu-exit": {"name": "EU Exit"},
    "events": {"name": "Events"},
    "everyone-counts": {"name": "Everyone counts"},
    "exceptions-to-spending-moratoria": {"name": "Exceptions to spending moratoria"},
    "expo": {"name": "Expo"},
    "extended-team": {"name": "Extended team"},
    "eye-health": {"name": "Eye health"},
    "finance": {"name": "Finance"},
    "five-year-forward-view": {"name": "Five Year Forward View"},
    "flexible-working": {"name": "Flexible working"},
    "flow-and-improving-system-pathways": {
        "name": "Flow and Improving System Pathways"
    },
    "flu": {"name": "Flu"},
    "friends-and-family-test": {"name": "Friends and Family Test"},
    "gambling-addiction": {"name": "Gambling addiction"},
    "gender-identity": {"name": "Gender identity"},
    "general-practice": {"name": "General practice"},
    "genomics": {"name": "Genomics"},
    "get-involved": {"name": "Get involved"},
    "governance": {"name": "Governance"},
    "governing-bodies": {"name": "Governing bodies"},
    "gp-and-practice-team-bulletin": {"name": "GP and practice team bulletin"},
    "gp-online-services": {"name": "GP online services"},
    "gp-patient-survey-dental-statistics": {
        "name": "GP Patient Survey Dental Statistics"
    },
    "gp-patient-survey": {"name": "GP Patient Survey"},
    "guest-blogs": {"name": "Guest blogs"},
    "health-and-housing": {"name": "Health and housing"},
    "health-and-justice": {"name": "Health and justice"},
    "healthcare-inequalities": {"name": "Healthcare inequalities"},
    "healthcare-science": {"name": "Healthcare science"},
    "healthy-new-towns": {"name": "Healthy new towns"},
    "hearing-loss": {"name": "Hearing loss"},
    "heart-disease": {"name": "Heart disease"},
    "hospital-estates-and-facilities-statistic": {
        "name": "Hospital estates and facilities statistic"
    },
    "hot-weather-news-and-advice": {"name": "Hot weather news and advice"},
    "identifying-and-responding-to-sexual-assault-and-abuse": {
        "name": "Identifying and responding to sexual assault and abuse"
    },
    "impact-assessments": {"name": "Impact assessments"},
    "improvement-tools": {"name": "Improvement Tools"},
    "inderjit-singh": {"name": "Inderjit Singh"},
    "individual-leaders": {"name": "Individual leaders"},
    "information-governance": {"name": "Information governance"},
    "information-standard": {"name": "Information Standard"},
    "informed": {"name": "Informed"},
    "innovation": {"name": "Innovation"},
    "integrated-care": {"name": "Integrated Care"},
    "integrated-performance-measures-monitoring": {
        "name": "Integrated Performance Measures Monitoring"
    },
    "jane-cummings": {"name": "Jane Cummings"},
    "john-holden": {"name": "John Holden"},
    "large-scale-change": {"name": "Large Scale Change"},
    "lead-provider-framework": {"name": "Lead Provider Framework"},
    "learning-disabilities": {"name": "Learning disabilities"},
    "liaison-and-diversion-bulletin": {"name": "Liaison and Diversion Bulletin"},
    "liaison-and-diversion": {"name": "Liaison and diversion"},
    "living-longer-lives": {"name": "Living Longer Lives"},
    "local-child-health-profiles": {"name": "Local Child Health Profiles"},
    "local-health-profiles": {"name": "Local Health Profiles"},
    "long-term-conditions": {"name": "Long term conditions"},
    "long-term-plan": {"name": "Long Term Plan"},
    "martin-mcshane": {"name": "Martin McShane"},
    "maternity": {"name": "Maternity"},
    "measurement": {"name": "Measurement"},
    "medical-directors-bulletin": {"name": "Medical directors' bulletin"},
    "medicine": {"name": "Medicine"},
    "mental-health-community-teams-activity": {
        "name": "Mental Health Community Teams Activity"
    },
    "mental-health": {"name": "Mental health"},
    "mike-bewick": {"name": "Mike Bewick"},
    "mike-durkin": {"name": "Mike Durkin"},
    "ministerial-gifts-hospitality": {"name": "Ministerial gifts & hospitality"},
    "ministerial-visits": {"name": "Ministerial Visits"},
    "mixed-sex-accommodation-breaches": {"name": "Mixed Sex Accommodation Breaches"},
    "monthly-hospital-activity-data": {"name": "Monthly Hospital Activity Data"},
    "musculoskeletal-conditions": {"name": "Musculoskeletal conditions"},
    "national-diet-and-nutrition-survey": {
        "name": "National Diet and Nutrition Survey"
    },
    "national-quality-board": {"name": "National Quality Board"},
    "national-quarterly-pulse-survey": {"name": "National Quarterly Pulse Survey"},
    "net-zero": {"name": "Net Zero"},
    "never-events": {"name": "Never Events"},
    "new-business-models": {"name": "New business models"},
    "new-care-models": {"name": "New care models"},
    "news-and-blogs": {"name": "News and blogs"},
    "news": {"name": "News"},
    "nhs-111-minimum-data-set": {"name": "NHS 111 Minimum Data Set"},
    "nhs-111": {"name": "NHS 111"},
    "nhs-accelerated-access-collaborative": {
        "name": "NHS Accelerated Access Collaborative"
    },
    "nhs-birthday": {"name": "NHS Birthday"},
    "nhs-dental-commissioning": {"name": "NHS Dental Commissioning"},
    "nhs-improvement": {"name": "NHS Improvement"},
    "nhs-payment-system": {"name": "NHS payment system"},
    "nhs-people-plan": {"name": "NHS People Plan"},
    "nhs-providers": {"name": "NHS providers"},
    "nhs-rightcare": {"name": "NHS RightCare"},
    "nhs-staff-survey": {"name": "NHS staff survey"},
    "nhs-standard-contract": {"name": "NHS Standard Contract"},
    "nhs70": {"name": "NHS70"},
    "non-consolidated-performance-related-payments": {
        "name": "Non-consolidated performance related payments"
    },
    "nursing-midwifery-and-care": {"name": "Nursing, midwifery and care"},
    "obesity": {"name": "Obesity"},
    "older-people": {"name": "Older people"},
    "olivia-butterworth": {"name": "Olivia Butterworth"},
    "operational-performance": {"name": "Operational performance"},
    "oral-health": {"name": "Oral health"},
    "out-of-hospital-care": {"name": "Out of hospital care"},
    "outpatient-transformation-programme": {
        "name": "Outpatient Transformation Programme"
    },
    "patient-and-public-engagement": {"name": "Patient and Public Engagement"},
    "patient-care": {"name": "Patient care"},
    "patient-experience": {"name": "Patient experience"},
    "patient-safety-alerts": {"name": "Patient Safety Alerts"},
    "patient-safety": {"name": "Patient safety"},
    "payment-of-suppliers": {"name": "Payment of suppliers"},
    "permanent-secretaries-meetings": {"name": "Permanent Secretaries meetings"},
    "personal-health-budgets": {"name": "Personal health budgets"},
    "personalised-care": {"name": "Personalised care"},
    "pharmacy": {"name": "Pharmacy"},
    "pimary-care": {"name": "Pimary Care"},
    "pip-breast-implants": {"name": "PIP breast implants"},
    "planning-guidance": {"name": "Planning guidance"},
    "prevention": {"name": "Prevention"},
    "primary-care-co-commissioning": {"name": "Primary care co-commissioning"},
    "primary-care": {"name": "Primary care"},
    "provider-bulletin": {"name": "Provider bulletin"},
    "public-appointments": {"name": "Public appointments"},
    "public-health-outcomes-framework": {"name": "Public Health Outcomes Framework"},
    "public-health": {"name": "public health"},
    "publications": {"name": "Publications"},
    "quality-improvement": {"name": "Quality improvement"},
    "referral-to-treatment-times": {"name": "Referral to Treatment Times"},
    "respiratory": {"name": "Respiratory"},
    "responses-to-campaigns": {"name": "Responses to campaigns"},
    "revalidation-matters-bulletin": {"name": "Revalidation Matters bulletin"},
    "revalidation": {"name": "Revalidation"},
    "roz-davies": {"name": "Roz Davies"},
    "safe-staffing": {"name": "Safe staffing"},
    "safeguarding": {"name": "Safeguarding"},
    "self-care": {"name": "Self care"},
    "senior-team": {"name": "Senior team"},
    "sepsis": {"name": "Sepsis"},
    "seven-day-services": {"name": "Seven day services"},
    "simon-bennett": {"name": "Simon Bennett"},
    "special-advisers-gifts-hospitality-media": {
        "name": "Special Advisers Gifts, Hospitality & Media"
    },
    "specialised-commissioning-stakeholder-bulletin": {
        "name": "Specialised Commissioning Stakeholder Bulletin"
    },
    "specialised-commissioning": {"name": "Specialised commissioning"},
    "spotlight": {"name": "Spotlight"},
    "spread-and-adoption": {"name": "Spread and Adoption"},
    "statistics-data-downloads": {"name": "statistics data downloads"},
    "statistics-information": {"name": "Statistics Information"},
    "statistics": {"name": "Statistics"},
    "stop-smoking": {"name": "Stop smoking"},
    "stroke": {"name": "Stroke"},
    "sustainability-and-transformation-partnerships": {
        "name": "Sustainability and transformation partnerships"
    },
    "sustainability": {"name": "Sustainability"},
    "system-transformation": {"name": "System Transformation"},
    "test-beds": {"name": "Test beds"},
    "test": {"name": "test"},
    "the-month": {"name": "The month"},
    "tim-kelsey": {"name": "Tim Kelsey"},
    "transition": {"name": "Transition"},
    "transparency": {"name": "Transparency"},
    "twelve-months-on": {"name": "Twelve months on"},
    "uncategorized": {"name": "Uncategorized"},
    "urgent-and-emergency-care": {"name": "Urgent and emergency care"},
    "vanguards": {"name": "Vanguards"},
    "volunteering": {"name": "Volunteering"},
    "vte-risk-assessment-data-collection": {
        "name": "VTE Risk Assessment data collection"
    },
    "waiting-times-for-suspected-cancer-patients": {
        "name": "Waiting Times for Suspected Cancer Patients"
    },
    "wheelchair-services": {"name": "Wheelchair services"},
    "whistleblowing": {"name": "Whistleblowing"},
    "whole-ccgs": {"name": "Whole CCGs"},
    "winter-health-check-reports": {"name": "Winter health check reports"},
    "winter-news-advice-and-blogs": {"name": "Winter news, advice and blogs"},
    "winter-news-and-advice": {"name": "Winter news and advice"},
    "winter-pressures-daily-situation-reports": {
        "name": "Winter Pressures Daily Situation Reports"
    },
    "workforce": {"name": "Workforce"},
    "young-carers": {"name": "Young carers"},
}

# Map a given Wordpress ID for a category type to a slug in the new categories list
CATEGORY_MAP = {
    "categories-commissioning": {
        "40": "6cs-live-bulletin",
        "41": "a-e-weekly-data",
        "42": "abortion-statistics-for-england-and-wales",
        "7": "about-us",
        "43": "admission-events-referrals-and-attendances",
        "112": "alistair-burns",
        "44": "allied-health-professionals-bulletin",
        "45": "ambulance-quality-indicators",
        "113": "ann-driver",
        "46": "annual-cancer-waiting-times-reports",
        "114": "barbara-hakin",
        "47": "bed-availability-and-occupancy",
        "48": "blogs",
        "8": "board-meetings",
        "49": "breastfeeding-quarterly-statistical-releases",
        "50": "bulletin-for-ccgs",
        "52": "business-plan-quarterly-data-summaries",
        "51": "business-plan-2012-2015-indicators-and-other-key-data",
        "9": "ccg-learning-and-support-tool",
        "10": "ccg-learning-network-news",
        "53": "cancelled-elective-operations",
        "54": "central-alerting-system-data",
        "56": "chief-scientific-officer-bulletin",
        "55": "chief-nursing-officer-bulletin",
        "57": "civil-service-people-survey-dh-results",
        "58": "commissioner-based-waiting-times-for-cancer-patients",
        "59": "commissioning-support-bulletin",
        "1243": "conflicts-of-interest-audit-and-training",
        "60": "consultant-led-referral-to-treatment-waiting-times-statistics",
        "61": "critical-care-bed-capacity-and-cancelled-urgent-operations",
        "66": "dh-business-expenses",
        "67": "dh-complaints",
        "62": "david-nicholson",
        "63": "delayed-transfers-of-care",
        "64": "departmental-spending-over-25000",
        "65": "departmental-spending-over-500",
        "68": "diagnostic-imaging-dataset",
        "69": "diagnostics-waiting-times-and-activity-data",
        "70": "direct-access-audiology-waiting-times",
        "71": "dr-johnny-marshall",
        "11": "everyone-counts",
        "72": "exceptions-to-spending-moratoria",
        "12": "expo",
        "13": "extended-team",
        "14": "friends-and-family-test",
        "74": "gp-patient-survey",
        "75": "gp-patient-survey-dental-statistics",
        "73": "gp-and-practice-team-bulletin",
        "15": "governing-bodies",
        "76": "guest-blogs",
        "77": "hospital-estates-and-facilities-statistic",
        "78": "impact-assessments",
        "79": "inderjit-singh",
        "17": "individual-leaders",
        "80": "informed",
        "81": "integrated-performance-measures-monitoring",
        "82": "jane-cummings",
        "83": "john-holden",
        "84": "liaison-and-diversion-bulletin",
        "85": "local-child-health-profiles",
        "86": "local-health-profiles",
        "87": "martin-mcshane",
        "88": "medical-directors-bulletin",
        "89": "mental-health-community-teams-activity",
        "90": "mike-bewick",
        "91": "mike-durkin",
        "93": "ministerial-visits",
        "92": "ministerial-gifts-hospitality",
        "94": "mixed-sex-accommodation-breaches",
        "95": "monthly-hospital-activity-data",
        "97": "nhs-111-minimum-data-set",
        "98": "nhs-dental-commissioning",
        "99": "nhs-staff-survey",
        "96": "national-diet-and-nutrition-survey",
        "18": "never-events",
        "19": "news",
        "100": "non-consolidated-performance-related-payments",
        "101": "olivia-butterworth",
        "105": "pip-breast-implants",
        "20": "patient-safety-alerts",
        "102": "patient-experience",
        "103": "payment-of-suppliers",
        "104": "permanent-secretaries-meetings",
        "1258": "primary-care",
        "106": "public-health-outcomes-framework",
        "21": "publications",
        "107": "responses-to-campaigns",
        "22": "revalidation-matters-bulletin",
        "108": "roz-davies",
        "23": "senior-team",
        "109": "simon-bennett",
        "110": "special-advisers-gifts-hospitality-media",
        "24": "specialised-commissioning-stakeholder-bulletin",
        "25": "statistics",
        "27": "statistics-information",
        "29": "the-month",
        "111": "tim-kelsey",
        "30": "transition",
        "31": "transparency",
        "32": "twelve-months-on",
        "1": "uncategorized",
        "34": "vte-risk-assessment-data-collection",
        "35": "waiting-times-for-suspected-cancer-patients",
        "36": "whole-ccgs",
        "39": "winter-pressures-daily-situation-reports",
        "37": "winter-health-check-reports",
        "38": "winter-news-advice-and-blogs",
        "1259": "commissioning",
        "1262": "integrated-care",
        "1261": "public-health",
        "1260": "specialised-commissioning",
        "26": "statistics-data-downloads",
        "28": "test",
    },
    "categories-improvement-hub": {
        "2": "7-days-consistency-of-care",
        "3": "acute-and-emergency-care",
        "4": "cancer",
        "5": "capability-building",
        "6": "cardiovascular",
        "7": "care-planning",
        "94": "coffee-break",
        "8": "community-services",
        "9": "culture-and-leadership",
        "10": "demand-and-capacity",
        "11": "diabetes-and-kidney-care",
        "12": "diagnostics",
        "13": "efficiency-and-waste-reduction",
        "14": "end-of-life-care",
        "15": "flow-and-improving-system-pathways",
        "16": "improvement-tools",
        "17": "innovation",
        "18": "integrated-care",
        "19": "large-scale-change",
        "20": "living-longer-lives",
        "21": "long-term-conditions",
        "22": "measurement",
        "23": "mental-health",
        "93": "news",
        "25": "patient-safety",
        "24": "patient-and-public-engagement",
        "26": "pimary-care",
        "27": "respiratory",
        "95": "spotlight",
        "28": "spread-and-adoption",
        "29": "stroke",
        "30": "sustainability",
        "31": "system-transformation",
        "1": "uncategorized",
    },
    "categories": {
        "3648": "a-greener-nhs",
        "21": "about-us",
        "2595": "academic-health-science-network",
        "2597": "accessible-information-standard",
        "3561": "ageing-well",
        "2599": "allied-health-professionals",
        "2603": "annual-report",
        "2604": "armed-forces",
        "3741": "asthma",
        "2894": "better-care-fund",
        "141": "board-meetings",
        "2610": "business-plan",
        "2523": "cancer",
        "2826": "carers",
        "2618": "children-and-young-people",
        "2832": "clinical-audit",
        "2521": "commissioning",
        "3698": "coronavirus",
        "3595": "culture-and-leadership",
        "2643": "dementia",
        "3754": "dental-care",
        "2524": "diabetes",
        "2648": "digital",
        "3499": "eu-exit",
        "2884": "efficiencies",
        "2527": "elective-care",
        "2650": "emergency-preparedness-resilience-and-response",
        "2835": "end-of-life-care",
        "2651": "equality-and-diversity",
        "3719": "estates",
        "2654": "events",
        "1672": "expo",
        "2895": "eye-health",
        "2874": "finance",
        "2656": "five-year-forward-view",
        "3757": "flexible-working",
        "3743": "flu",
        "1645": "friends-and-family-test",
        "2565": "gp-online-services",
        "3760": "gambling-addiction",
        "2875": "gender-identity",
        "2560": "general-practice",
        "2659": "genomics",
        "2687": "get-involved",
        "2827": "governance",
        "2661": "health-and-housing",
        "2662": "health-and-justice",
        "3766": "healthcare-inequalities",
        "2878": "healthcare-science",
        "2665": "healthy-new-towns",
        "2896": "hearing-loss",
        "2632": "heart-disease",
        "2041": "hot-weather-news-and-advice",
        "3758": "identifying-and-responding-to-sexual-assault-and-abuse",
        "2672": "information-standard",
        "2671": "information-governance",
        "2674": "innovation",
        "2679": "integrated-care",
        "2688": "lead-provider-framework",
        "2298": "learning-disabilities",
        "2691": "liaison-and-diversion",
        "3444": "long-term-plan",
        "2502": "long-term-conditions",
        "2056": "maternity",
        "2696": "medicine",
        "2297": "mental-health",
        "3449": "musculoskeletal-conditions",
        "2705": "nhs-111",
        "3677": "nhs-birthday",
        "3586": "nhs-improvement",
        "3686": "nhs-people-plan",
        "3687": "nhs-people-plan",
        "2716": "nhs-rightcare",
        "2717": "nhs-standard-contract",
        "2715": "nhs-payment-system",
        "3725": "nhs-providers",
        "3310": "nhs70",
        "3221": "national-quality-board",
        "3730": "national-quarterly-pulse-survey",
        "3235": "new-business-models",
        "2245": "new-care-models",
        "2735": "nursing-midwifery-and-care",
        "2893": "obesity",
        "2718": "older-people",
        "3597": "operational-performance",
        "2644": "oral-health",
        "3562": "out-of-hospital-care",
        "3752": "outpatient-transformation-programme",
        "2723": "patient-care",
        "1508": "patient-safety",
        "2729": "personal-health-budgets",
        "2681": "personalised-care",
        "2731": "pharmacy",
        "2732": "planning-guidance",
        "3563": "prevention",
        "2525": "primary-care",
        "2733": "primary-care-co-commissioning",
        "3593": "provider-bulletin",
        "3596": "quality-improvement",
        "2877": "referral-to-treatment-times",
        "2892": "respiratory",
        "2928": "revalidation",
        "2751": "safe-staffing",
        "2752": "safeguarding",
        "2755": "self-care",
        "2756": "sepsis",
        "2757": "seven-day-services",
        "2666": "specialised-commissioning",
        "3769": "stop-smoking",
        "3358": "stroke",
        "2512": "sustainability-and-transformation-partnerships",
        "2764": "test-beds",
        "2526": "urgent-and-emergency-care",
        "2771": "vanguards",
        "2315": "volunteering",
        "2773": "wheelchair-services",
        "2774": "whistleblowing",
        "1452": "winter-news-and-advice",
        "2876": "workforce",
        "3771": "young-carers",
    },
    "categories-aac": {
        "10": "artificial-intelligence",
        "3": "nhs-accelerated-access-collaborative",
        "4": "news",
        "1": "uncategorized",
    },
    "categories-rightcare": {
        "7": "blogs",
        "40": "nhs-rightcare",
        "4": "news",
        "41": "sepsis",
    },
    "categories-coronavirus": {
        "4": "covid-19",
        "3": "coronavirus",
        "2": "news",
        "1": "uncategorized",
    },
    "categories-greenernhs": {
        "9": "net-zero",
        "5": "news-and-blogs",
        "1": "uncategorized",
    },
    "categories-non-executive-opportunities": {
        "2": "public-appointments",
        "1": "uncategorized",
    },
}
