# created by menu_structure_creator.py
new_pages = ["programmes", "initiatives", "finance", "celebrate"]

menu_structure = [
    ["Publications", "/publication/"],
    [
        ["NHS England & Improvement", "/publication/nhs-england-improvement/"],
    ],
    ["Our work", "/ourwork/"],
    [
        ["Our work", "/ourwork"],
        ["Programmes of work", "/programmes/"],
        [
            ["Cancer", "/cancer/"],
            ["Coronavirus", "/coronavirus/"],
            ["Diabetes", "/diabetes/"],
            ["Friends and family test", "/fft/"],
            ["Genomics", "/genomics/"],
            ["Health Systems Support framework", "/hssf/"],
            ["Learning disabilities", "/learning-disabilities/"],
            ["Mental health", "/mental-health/"],
            ["Medicines: improving outcomes and value", "/medicines-2/"],
            ["Right Care", "/rightcare/"],
            ["Shared decision making", "/shared-decision-making/"],
            ["Urgent and emergency care", "/urgent-emergency-care/"],
        ],
        ["New Initiatives", "/initiatives/"],
        [
            ["Long term plan", "/long-term-plan/"],
            ["New care models", "new-care-models/"],
            ["Healthcare science", "/healthcare-science/"],
            ["Integrated care pioneers", "/integrated-care-pioneers/"],
            [
                "Personalised health and care framework",
                "/personalised-health-and-care-framework/",
            ],
            ["Digital transformation", "/digitaltechnology/"],
            ["Elective care transformation", "/elective-care-transformation/"],
            ["Integrated care", "/integratedcare/"],
            ["Primary care", "/primary-care/"],
            ["General Practice", "/gp/"],
            ["GP online services", "/gp-online-services/"],
            ["Nursing and midwifery", "/nursingmidwifery/"],
            ["Medical revalidation", "/medical-revalidation/"],
            ["Allied Health professions", "/ahp/"],
            ["Maternity transformation programme", "/mat-transformation/"],
            ["Chief Nursing Officer for England's Summit", "/cno-summit/"],
            [
                "International Year of the Nurse and Midwife 2020",
                "/year-of-the-nurse-and-midwife-2020/",
            ],
        ],
        ["Commissioning", "/commissioning/"],
        ["Finance and Governance", "/finance/"],
        [
            [
                "Increasing Health and Social Care Worker Flu Vaccinations: Five Components",
                "/increasing-health-and-social-care-worker-flu-vaccinations/",
            ],
            [
                "Business case approval process – Capital Investment, Property, Equipment and Digital Technology",
                "/bus-case",
            ],
            ["NHS payment system", "/pay-syst"],
            [
                "NHS providers: financial accounting and reporting",
                "/financial-accounting-and-reporting",
            ],
            ["Data Services", "/data-services"],
            ["Information governance", "/ig"],
            ["The information standard", "/tis"],
        ],
    ],
    ["NHS Workforce", "/our-people"],
    [
        ["NHS Workforce", "/our-people"],
        ["NHS People Plan", "/ournhspeople/"],
        ["Looking after our people", "/looking-after-our-people/"],
        ["Pensions", "/pensions/"],
        ["Celebrating NHS", "/celebrate/"],
        [
            ["NHS birthday 2020", "/nhsbirthday/"],
            ["@ NHS", "/atnhs"],
            ['"NHS Parliamentary awards"', "/nhs-parliamentary-awards"],
        ],
    ],
    ["Learning and Improvement", "/improvement"],
    [
        ["Learning and Improvement", "/improvement"],
        ["Improvement hub", "/improvement-hub/"],
        ["Patient safety", "/patient-safety/"],
        ["Safeguarding", "/safeguarding/"],
        # ["Insights platform", "/insights-platform/"], # 404 on live
        ["Always events", "/always-events/"],
        ["Evidence-Based Interventions Programme", "/evidence-based-interventions/"],
        [
            "Menu of evidence-based interventions and approaches for addressing and reducing health inequalities",
            "/ltphimenu/",
        ],
        ["7 day hospital services", "/seven-day-hospital-services/"],
        ["Winter resilience", "/winter/"],
        ["NHS Accelerated Access Collaborative (AAC)", "/aac/"],
        ["A greener NHS", "/greenernhs/"],
    ],
    ["Get Involved", "/get-involved/"],
    [
        ["Get Involved", "/get-involved/"],
        ["About the involvement hub", "/get-involved/about/"],
        ["How to get involved", "/get-involved/get-involved/"],
        ["Why get involved", "/get-involved/why/"],
        ["Current opportunities", "/get-involved/get-involved/opportunities/"],
        ["Learning and development", "/get-involved/learning/"],
        # ["Surveys and consultations", "https://www.engage.england.nhs.uk/"],
        ["Good practice and case studies", "/get-involved/success/"],
        [
            "Resources and bite sized guides",
            "/get-involved/resources/bitesizeparticipation/",
        ],
        ["Information for commissioners", "/get-involved/involvementguidance/"],
    ],
    ["News and blogs", "/news/"],
    [
        ["News", "/news/nhs-england-improvement/"],
        ["Blogs", "/blogs/blog/"],
        ["Events", "/events/"],
    ],
]
